version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "5174:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
